- hosts: all
  become: no
  become_method: sudo
  tasks:
    - name: install python package
      become: yes
      package:
        name:
          - python3-apt
          - apache2
        state: latest
    - name: copy conf file
      become: yes
      copy:
        src: config/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644
    - name:
      ...